eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/zouxiangzhong1998/spring-cloud-finchley-config-repo.git
          basedir: D:\Documents\Workspaces\Carlos\idea-workspaces\spring-cloud-finchley\config\basedir
  rabbitmq:
    host: 139.199.211.226
    port: 5672
    username: guest
    password: guest
management:
  endpoints:
    web:
      exposure:
        include: "*"